#!/bin/bash

cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
. build/envsetup.sh
lunch styx_ysl-userdebug
export SELINUX_IGNORE_NEVERALLOWS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

# Telgram env setup
export BOT_MSG_URL="https://api.telegram.org/bot$API_BOT/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$API_BOT/sendDocument"

tg_post_msg() {
        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
        -d "parse_mode=html" \
        -d text="$1"
}

# stuffs
up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	m api-stubs-docs
	m system-api-stubs-docs
	m test-api-stubs-docs
}

make_rom(){
	tg_post_msg "<b>StyxOS CI Build Triggered for ysl</b>" "$CHATID"
	m styx-ota -j14
	url=$(up out/target/product/ysl/*zip)
	echo " "
	echo "$url"
	tg_post_msg "<b>Build Completed</b>%0A%0A<b>Link : </b> <code>"$url"</code>" "$CHATID"
}

make_metalava
make_rom
