#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

ccacheurl=https://server.nippon.workers.dev/ccache/ci2/styxysl_ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $ccacheurl -x16 -s50 || time aria2c $ccacheurl -x16 -s50
time tar xf styxysl_ccache.tar.gz
find styxysl_ccache.tar.gz -delete
