#!/bin/bash

mkdir -p /tmp/rom/aosp # Where to sync source
cd /tmp/rom/aosp

git config --global user.name "gamehackerever"
git config --global user.email "gamehackerever@gmail.com"

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u https://github.com/PixelExtended/manifest -b eleven -g default,-device,-mips,-darwin,-notdefault

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
#git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# device stuff
git clone https://github.com/gamehackerever/device_xiaomi_vince -b testing device/xiaomi/vince
git clone https://github.com/gamehackerever/vendor_xiaomi_vince -b staging vendor/xiaomi/vince
git clone https://github.com/Blacksuan19/kernel_dark_ages_vince.git --single-branch -b darky kernel/xiaomi/vince
rm -rf hardware/qcom-caf/msm8996/display && git clone https://github.com/smokey18/hardware_qcom_display hardware/qcom-caf/msm8996/display
rm -rf hardware/qcom-caf/msm8996/audio && git clone https://github.com/smokey18/hardware_qcom_audio hardware/qcom-caf/msm8996/audio
rm -rf packages/apps/Camera2
rm -rf hardware/qcom-caf/msm8996/media && git clone https://github.com/smokey18/hardware_qcom_media hardware/qcom-caf/msm8996/media
rm -rf hardware/qcom/wlan && git clone https://github.com/Jabiyeff-Project/android_hardware_qcom_wlan hardware/qcom/wlan
cd kernel/xiaomi/vince && git checkout darky && git revert fec013b9f5bb70c1e51285aa6e042f21f4298447 --no-edit && cd ../../..
rm -rf hardware/qcom-caf/wlan && git clone https://github.com/PixelExperience/hardware_qcom-caf_wlan hardware/qcom-caf/wlan
